<a href="https://colab.research.google.com/github/yasthika-baskaran/ML-LAB/blob/main/165ex8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
from google.colab import files
files.upload()

Saving heartdisease exp 8.xlsx to heartdisease exp 8.xlsx

{'heartdisease exp 8.xlsx': b'PK\x03\x04\x14\x00\x06\x00\x08\x00\x00\x00!\x00\xe3\xec\x16Y]\x01\x00\x00\x99\x04\x00\x00\x13\x00\x08\x02[Content_Types].xml \xa2\x04\x02(\xa0\x00\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xac\x94\xcfN\x021\x10\x87\xef&\xbe\xc3\xa6W\xc3\x16<\x18cX8\xf8\xe7\xa8$\xe2\x03\xd4v\x96mh;Mg\xc0\xe5\xed\xcd\x16AcV\x88\x81\xcb\xf6\xb0\xd3\xdf\xf7u\xd2\xe9x\xdazW\xac!\x91\xc5P\x89Q9\x14\x05\x04\x8d\xc6\x86E%\xde\xe6O\x83[Q\x10\xab`\x94\xc3\x00\x95\xd8\x00\x89\xe9\xe4\xf2b<\xdfD\xa0\xa2\xf5.P%\x1a\xe6x\'%\xe9\x06\xbc\xa2\x12#\x84\xd6\xbb\x1a\x93WL%\xa6\x85\x8cJ/\xd5\x02\xe4\xf5px#5\x06\x86\xc0\x03\xee2\xc4d\xfc\x00\xb5Z9.\x1e[\x86\xb05I\xe0H\x14\xf7\xdb\xc2\x8eU\t\x15\xa3\xb3Z\xb1\xc5 \xd7\xc1\xfc\xa2\x0c\xbe\x08e\x02\x97k\xa8\xb1\x91\xaeZ\xefD!{\x11\xf9\xd7\x9f\x84\xdd\xc6\x975\xa4d\r\x143\x95\xf8Yy\xa8\x84l\x9d\xfc\xc0\xb4|G\\\x96\x87Sz<\xb1\xae\xad\x06\x83z\xe5!pI1\x812\xd4\x00\xb0we^K\xafl\xd8\x9b\x1f\x10\xc8\xd5$\xf32:\xb3Iw\xc0\x1c|L\x84\x1b\xf0 \xf3\xf7t\x87\x1cs\x8cH\xbcq@\xe7\xee|\x0e=\x8anT\x02\xf3\xca\xc9\x86\xc5\xd9\r~f\x1f\x141\xa8g\t#I\x8d\t\xfe\xdf\x87\xdd\xa4t\xbb\x071a\x84\xc4\x16\xbeg\xa5\xef\xc6\xed\x91*\xc6\x93;\x0f\xdd\x9c\x1b0}p\x99\x1f\x96\xc9\'\x00\x00\x00\xff\xff\x03\x00PK\x03\x04\x14\x00\x06\x00\x08\x00\x00\x00!\x00\x97\x08E\x98\xf1\x00\x00\x00O\x02\x00\x00\x0b\x00\x08\x02_rels/.rels \xa2\x04\x02(\xa0\x00\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xac\x92\xc1J\x031\x10@\xef\x82\xff\x10\xe6\xde\x9dm\x05\x11i\xb6\x17\x11z\x13Y?`L\xa6\xbba\x93LH\xa2n\xff^\xbc\xa8\x0b\xb5\xf4\xe0}x\xf3\xe61\xdb\xdd\x1c\xbcz\xe7\\\x9cD\r\xeb\xa6\x05\xc5\xd1\x88uq\xd0\xf0\xd2?\xae\xee@\x95J\xd1\x92\x97\xc8\x1a\x8e\\`\xd7]_m\x9f\xd9Su\x12\xcb\xe8RQs\xf0\xb1h\x18kM\xf7\x88\xc5\x8c\x1c\xa84\x928\xce\xc1\x1f$\x07\xaa\xa5\x91<`"3\xd1\xc0\xb8i\xdb[\xcc\xbf\x19\xd0-\x98jo5\xe4\xbd\xbd\x01\xd5\x1f\x13_\xc2\x96\xc3\xc1\x19~\x10\xf3\x168\xd6\x13+\x90\xe7\xca\xd1\xb2]\xa5,\x89su\\@\xf5\x94\x07\xae\x1a\xac\x98\xa7,\xa9 \xa5\xd4\xcc\xc1\x83\xc2\xd3J\x9b\xcb\x95\xfe>\x17\x03W\xb2T\t\x8dd>/\xf45q\xd6h\xfd\x9f\x91\x96\x19\x7f\xfa\xcc\x1e?$O\xaf"\xd3\xb7\x0c.\xde\xa0\xfb\x04\x00\x00\xff\xff\x03\x00PK\x03\x04\x14\x00\x06\x00\x08\x00\x00\x00!\x00\xcd6\xe0\x01r\x03\x00\x00g\x08\x00\x00\x0f\x00\x00\x00xl/workbook.xml\xa4V[k\xe38\x14~_\xd8\xff \xf4\xeeZr|\x8b\x89=8N\xcc\x16\xda\x12\xdal\xbb\x0b\x81\xa0\xcaJ,j[^IN]\xca\xfc\xf7A\xce\xa5\xd3\xe9\xb0d:y\x90\xa2\xa3\xa3\xef\xdc\xbes\x92\xc9\x97\xbe\xae\xc0\x8eI\xc5E\x13C|\x81 `\r\x15\x05o\xb61\xfc{\x99[!\x04J\x93\xa6 \x95hX\x0c_\x98\x82_\x92?\xff\x98<\x0b\xf9\xf4(\xc4\x13\xe8\xeb\xaaQ1,\xb5n#\xdbV\xb4d5Q\x17\xa2eM_W\x1b!k\xa2\xd5\x85\x90[[\xb5\x92\x91B\x95\x8c\xe9\xba\xb2\x1d\x84|\xbb&\xbc\x81{\x84H\x9e\x83!6\x1bN\xd9L\xd0\xaef\x8d\xde\x83HV\x11\xcdE\xa3J\xde\xaa#ZM\xcf\x81\xab\x89|\xeaZ\x8b\x8a\xba%\x9a?\xf2\x8a\xeb\x97\x01\x14\x82\x9aF\x97\xdbFH\xf2X\xb1\x18\xf6\xd8\x03\xbd\x04\xbd\xf4A/1\x02\xbdt\x8e\x96z\xec}0Us*\x85\x12\x1b}AEm\xef\x9d\xfe\x10?F6\xc6\xefR\xd0\x7f\xcc\xc1yH\xae-\xd9\x8e\x9b\x1a\x9e\xbc\x92\xfe\'\xbd\xf2OX\xfe\x1b\x18F\xbf\x8d\x86\xd1\x1b\x9c\xf3I4\xef\xe4\x9b\x03\x93\xc9\x86W\xec~O]@\xda\xf6\x86\xd4\xa6R\x15\x04\x15Qz^p\xcd\x8a\x18\x06\x10T\xe2\x99\xbd\x13\xc8\xae\x9dv\xbc*b\xe8\x84\xa1\x13@`\'\'>/$(\xd8\x86t\x95^\x96\xac>\xe2\xc7\x10\xfb\xfe\xd8\xf1\x06\xd5\x9aFi\xa5\x99l\x88f\x99h4k\xf4\x81\xc3\xbf\xcb\xbadR\xd3(+\x05\xa7\x0c\xdc\xb2\xff:.\x99\x1a\xc8\x07\x93I\x8f=B#\xf2\xa8\x16D\x97\xa0\x93U\x0c\xb3h\xf5\xc0\x9bB<\xab\xd5\x1d\x93;N\xd9B\n\x93\x15\xb5\xbaa\xdat\xe8A\xbcJ\xdbvF4Y]\tJ\xaa\xd5\x82\xd0\'\xb2eje\x0c\xad\xb1\xbf\x1e\x07\xee\x86x\x81\xbf\x1e9\x14\x17#\xec\xae\x1d6B\xab4[-Y\xdd\xae\xbe\xa3:\xf9\xd8W\xbf@vB\x87\x04\xda\xa7(\x93\x89\xf9\xfec6\x93I/\xa3#\xa3\x17Z\x02\xc9v\x97\xb3+\xa2\xf4\x1d\xd9\xb1\x18"\x08\x8a\xc3\x08\xb8,b\x18\xae_\xc3`\x9e\x8d\xb2YfM\xb3\xc0\xb5\xbc\xd0\xf5\xad4\xc7\x995Es\x07\xb9\xf9\xc8\x0b\xe6\xc1Wh\xfa7\xa2\x82t\xba<\xf0\xc6`\xc6\xd0\r~ruM\xfa\xe3\rFQ\xc7\x8b7\xfb\xaf\xe8\xf0\xb1\xcc\xfe\xc3r\xbc\xfb:\x84jF\xe4=g\xcf\xea\x8da\xe6\x08\xfa}\xe1bh\xf9\x08\x82\x97w\xa7\xe7\xa1\xa6\x0f\xbc\xd0e\x0c\xb1\xe7\x86\x08\x82\xbd\xec/\xc6\xb7\xa5\x8e!\xc6\xbek\xdaI:\xc6\xb1\x18\xbe\x06\x9e\x8b\xf2<p\xad|\x9cf\x96\x8b\\l\x85\xa3Qj\x8d\xdc\x00\xe10\xc73\x8c\xdc\xbdC\xf6w\x1e\r\xb3X%\x93a\x07\xcd\xd0?f \x0fg\x93Y\x0c\x81\x8c\x8c\x01yY\xe0}\xe9\x8eo(\xa9\xe8B\x02\xb3\r\x9ac\x8c\x9cpPa\xbd\xbeR:\x99\xb0^\x83N\xf2\x18\xbeN\xbdp\x8aFc\xc7rs\x9c[.\x1e#k:\xf5]\xcb\x9b\x99\xca\xe0Y6\xf7rS\x1d\xf3K\x12\xf5\x06r\xf3\xc9\x01\x11\xda\xc3kFt\'\x992]3\x9c#\xb3\xe6\x07\xe9I\xb8\xd9\x0b\x0e\x81\xbf\xa3qt;\x1bb9<\xff?\xcd;\xdel+v\xaev~\x7f\xaefvs\xbd\xbc>W\xf9j\xbe\\?\xe4gk\xa7\xd7\xd3Y\xfa\x0b\x0f\xd2\xdb\xdb\xf4\xdf\xe5\xfc\x9f\x93\x11\xfb\xa7y\xb5Y\xaf\x93\x89Y\x07\x02\xd8\xc7\xff\x08\xc97\x00\x00\x00\xff\xff\x03\x00PK\x03\x04\x14\x00\x06\x00\x08\x00\x00\x00!\x00\x05\tGo\xf3\x00\x00\x00\xbe\x02\x00\x00\x1a\x00\x08\x01xl/_rels/workbook.xml.rels \xa2\x04\x01(\xa0\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xacR\xcbj\xc30\x10\xbc\x17\xfa\x0fb\xef\xb5\xec\xb4\x94R"\xe7\x12\n\xb9\xb6\xee\x07\x08{-\x89\xe8a\xb4\xdb\xd6\xfe\xfb\x82\x0b\x89\x03!\xf4\xe0\xcb\xc2\xcc\xc2\xcc\xb0\xb3\xdb\xdd\x18\xbc\xf8\xc6L.E\x05UQ\x82\xc0\xd8\xa6\xceE\xa3\xe0\xb3y{x\x01A\xacc\xa7}\x8a\xa8`B\x82]}\x7f\xb7}G\xaf\xd9\xa5H\xd6\r$\xc6\xe0#)\xb0\xcc\xc3\xab\x94\xd4Z\x0c\x9a\x8a4`\x1c\x83\xefS\x0e\x9a\xa9H\xd9\xc8A\xb7GmPn\xca\xf2Y\xe6\xa5\x06\xd4\x17\x9a\xe2\xd0)\xc8\x87\xee\x11D3\r\xf8\x1f\xed\xd4\xf7\xae\xc5}j\xbf\x02F\xbeb!\x89\'\x8f\x04\xa2\xd1\xd9 +\xf8\xc3\xc5\x18<\x08y\xdd\x7f\xb3\xa6?[\x0cx\xb6\x9f\xa1\x9cgu3D\xb5f\x88\x9f\x94\x8fd\x11\xf9\x1c\xe4D\x91\x9c7\xb7\xd3<\xadZ\x89\xd5\x19\xbb\x0f\xce.\x9ae3K\xfat\x1by\xf1u\xf5/\x00\x00\x00\xff\xff\x03\x00PK\x03\x04\x14\x00\x06\x00\x08\x00\x00\x00!\x00yI\xed\xe2V\x04\x00\x00<\x14\x00\x00\x18\x00\x00\x00xl/worksheets/sheet1.xml\x9c\xd2\xcd\x8e\xda0\x10\x00\xe0{\xa5\xbe\x835\xf7\xc4q\x08\x14"\xcc\x8a\x92\xa5\xdd[\xd5\xee\xf6n\x9c\t\xb1\xf0Od\x9b%\xa8\xea\xbbW\tZ\xb6\x12\x17\xb47\xcb\xf2|3\xe3\x99\xe5Co4yE\x1f\x94\xb3\x1cX\x9a\x01A+]\xad\xec\x9e\xc3\xcb\xf36\x99\x03\tQ\xd8Zhg\x91\xc3\x19\x03<\xac>\x7fZ\x9e\x9c?\x84\x161\x92\xdeh\x1b8\xb41v%\xa5A\xb6hDH]\x87\xb67\xbaq\xde\x88\x18R\xe7\xf74t\x1eE=\x06\x19M\xf3,\x9bQ#\x94\x85\x8bP\xfa{\x0c\xd74Jb\xe5\xe4\xd1\xa0\x8d\x17\xc4\xa3\x16Q9\x1bZ\xd5\x857\xcd\xc8{8#\xfc\xe1\xd8%\xd2\x99ND\xb5SZ\xc5\xf3\x88\x021\xb2|\xda[\xe7\xc5N#\x87\x9e\x15B\x92\xde\x93\xde\xe7\xa4\xf7\x93\xb74\xe3\xfdM&\xa3\xa4w\xc151\x95\xce\xd0K\xcd\xb7\xed/\xe8\x82\ny\x95n\xfb\xbf\x8ba\x05\xf5\xf8\xaa\x86\x01\xbeS\xf9\xc7Jb\xd3\xab\x95\xbfc\x93\x0fb\xb3+6|\x97/\x8f\xaa\xe6\xf0g;\x9dU\x9by>K\x16l\xb2I\x8aj\xca\x92\xf5\xe3c\x91|YL\xd9\xa6\xfa\xba.\xd6\xf3\xc9_X-ke\xd0\x0e]\x11\x8f\r\x875+\xbf\xe5\x19\x10\xbaZ\x8e\x1b\xf4[\xe1)\xfcw&Q\xec~\xa1F\x19\xb1\xe6\xc0\x80\x0c\x0b\xbas\xee0<|\xaa9\\b\xe9M\xf0v\xdc\xd0\x1f\x9e\xd4\xd8\x88\xa3\x8e?\xdd\xe9;\xaa}\x1b9\xb0)\x90q\xc0e}\xae0H\xb4\x91C\x96\xe6C\x15\xff\x00\x00\x00\xff\xff\x00\x00\x00\xff\xff\x94\x98[n\xdb@\x0cE\xb7bh\x01\xb5G~%\x81,\xa0\xa3y\xac\xc3p\r\xf4+),#iw_\xc4$R\xf1\xf2\xa2\xc0\xfc\x1e\x12\x1c\x1fq\x1eL\x86\xf9\xe7\xf5zO\xe7\xfby\x1cno\x1f\xab\xdb\xa9\x0b\xddj\xfeu~\x9dO]x9v\xab\xdfaw\xbe\xbc\xfc\xf8\x93\xae\xf3\xe5\xfaz?u\x9bo}7\x0e\x97\xcf\xd4\xef\xa1[\xddO\xdd\xdc\x8d\xc3\xfb\xb8\x19\xd6\xef\xe3\xb0\xbeh,.c\xc1\xc6\xa6e\xac\xb7\xb1\xb4\x8cmm,/c;\x1b+\xcb\xd8\xde\xc6\xea2v\xf8\x8a\xadoo\x1f_\xda}\x83\xf6\xe7\x07\xf0\xc2\x94NB\xe1\x03$J\xb3P\x90.\xb4n\xc5\nFf\xdb \xb3\xa52B\xb1o\x94&J\xb3P\x94\xa1\xabU\xac`dv\r2\xbb\x87\x0c\xfc\xec(\x146\xe8Di\xa24\x0b\x85\xadZ\xe8j\x15\xa9\x91\xd97\xc8\xec\x1f2\xb0\xcf\xa3P\x94\x11\x8a\xdb\x8c\xd2,\x14;#\x14\x14+\xaefd\x0e\r2\x87\x87\x0c,\x1a\x85\xe26\xa34\t\x05\xf1Li\x11\x8a2\x98kd\x8e\r2\xc7\x87\x0c\x94\x8fB\xb13B\xb13\x94fJ\x0b\xad[1\xd7\xc8<5\xc8<\xd1m&\x14e\x84\xa2\x0c\xcd\xcdB\xf1\xcc\xd0\xdc\x8au\x8d\xccs\x83\xcc3\xbd\xcd(\x9d\x84\xa2\x0c\xa5Y(\x9e\x19Z\xb7b\x05#\x136-\xef\xeb\x86\x9e\x9a \xd8\xbd\xaa\x14\'\xcd\xc6\x83\xc3qQ\x8cG\xc7e[\xa9\xa6\xa1!\xd0K:P<)\x86_\x9f8\xce\x1c\x17\xc5N\n\x97\xb4R-#A\x90\xf7\x18/k\xc5\xaeS\xf4MO<;+\xc6\x93\xa4\x18\xbeLuE\xacT\xcbh\x10\xe4]vR\xf4\x11\x9f4\x1b\xcf\x13\xc7Y1\x9e(\xc5\xaeS\xb8\xa4\x95j\x19\x11\x02}\xcb\xa3b\xd7)>%h\xb6;S4\xbb\xf0\xec\xea\xb0\x95j\x19\x15\x02}\xbd\xa3b\xbc\xc5\x15\xbbN\xf1q\x81g\x17^\xbb\xbal+\xd522\x04>3(v\x9d\xe2S\x83f\xbbN\xf1\xb9\x81\xd7\xae\xae\x88\x95j\x19\x1d\x02}\xcd#\xc7\x93b\xd7)Z$\xf3"E\xb1;S\xff\x9d B\xcb\x08\x11\xe8\\\x109\x9e\x14\xbb+\x9d\x16\xc9\x9a\xedn?\x9a]\xdd\x92\xb6S-\xa3D\xa0o~T\xec\xb6\x1f\x9f&xvV\x0c\x9f\xa0\xf0\xec\xea\xb2\x8dT\xdf2Q\xf42#\xe0\x95\xae\x18/\n\xc5\xee\xafW:hd\xcdv\x7f\xbfJ6n?\xb7\xa4H\xad\xff\xfdG\xe2/\x00\x00\x00\xff\xff\x00\x00\x00\xff\xff\xb2)HLO\xf5M,J\xcf\xcc+V\xc8IM+\xb1U2\xd03WR(\xcaL\xcf\x80\xb1K\xf2\x0b\xc0\xa2\xa6J\nI\xf9%%\xf9\xb90^FjbJj\x11\x88g\xac\xa4\x90\x96\x9f_\x02\xe7\xe8\xdb\xd9\xe8\x97\xe7\x17e\x17g\xa4\xa6\x96\xd8\x01\x00\x00\x00\xff\xff\x03\x00PK\x03\x04\x14\x00\x06\x00\x08\x00\x00\x00!\x00\xd6\xbe\r\xb6]\x07\x00\x00\xa4!\x00\x00\x13\x00\x00\x00xl/theme/theme1.xml\xecZ\xcd\x8f\xdb\xc6\x15\xbf\x17\xe8\xff0\xe0]&\xf5A}\xc1\xdc@\xa2$o\xec]\xdb\xb0d\x179\xbe\xa5F\xe4x\x873\xc2\xcchw\x85\xc0@\xe1\x9cz)P \tz)\xd0[\x0fE\xd1\x00\r\xd0\xa0\x97\xfe1\x06b\xb4\xe9\x1fQ\xcc\x90\x129+2^\xc7\x9b EW\xba\x88\xe4{\xf3~\xefc\xde{z\x9c\xfb\x1f]\xa5\x14]`!\tg\x81\xd3\xbc\xe79\x08\xb3\x88/\t\x8b\x03\xe7\xf9b\xd6\xe8;H*`K\xa0\x9c\xe1\xc0\xd9b\xe9|t\xf4\xcb_\xdc\x87\xa1Jp\x8a\xd1UJ\x99\x1cB\xe0$J\xad\x87\xae+\xa3\x04\xa7 \xef\xf15fW)]q\x91\x82\x92\xf7\xb8\x88\xdd\xa5\x80K\xc2\xe2\x94\xba-\xcf\xeb\xba)\x10\xe6 \x06)\x0e\x9c\'\xab\x15\x890jy\xcd6j\xa0\x96\xd7j\xa1\x85^\xde9\xda\t\x9aR\x9cb\xa6\xa4\xbe\x11Q1\xd7bp-\xb7\xe1[\x9e75\xb5\xdc\xca\x90\nt\x014p.\t[\xf2\xcb\x05\xbeR\x0e\xa2 UHE\xe0x\xe6\xe3 \xf7\xe8\xbe\x0b\xc3\x9c\x8b\xaa\x1a\xe6\x12\xe3\xcc|v\x8c9\xc7\xf2\xbce\xa4\x8a\xf8l/\xb6\xd3\xf1;\xddQ!\xc1PPuH8\xedM\xbb\xd3n\xb1\xa2\xa1\x80(\xc2,\x87c\xaf\xdak\x85\x9d\x1dq\x89*\xfbY\xb1\xfa\xa47i7m\x86\x92\x84\xf6\x01\xee\x91\xaf\xbf6\x83\xa1\xca$t\x0e\x18f\xb3\xd0\xf3<\x9b\xc1Pe\x0c\xfe\x01\x83?\x1e\x8c\'\xd7$\x18\xaa\x8c\xa1{\xc0\xd0\xf3F\x93N\xcf\x96`\xa8\x12J\xd8\xf9\x01\xb9\xe7w\xdb\xe1^\xe5=\xcd\x8a\xd3\xe3J\xfa\x81\xdf\x99\xf5Z\xbb\xe5\x0b2\xb7\x14uZ\xc8\x8a3u\x93\x18L\xe1%\x173\xce\x94f\xa2\xa0\x08Cj\xbb\xc6+\x88p\xe0\x84@\xc9\x99 \xe8\x84\xc4\x89r\xd0\x1a\x18\x978p\xbc\x967\xf3\xda^\xcb|;\xe6W\xe6e\x18b(\xb1\x1b\x940\x8c\xe4\xe1=\r\x0f\xc9H\x90\xb5\n\x9c\x87k`N\x89\xe6\xdbo\xbey\xf3\xfa\xeb7\xaf\xff\xfe\xe6\xb3\xcf\xde\xbc\xfe\xebN\xbc\xbb\xd3k\xcfx\x0c,.3~\xf7\xa7\xdf\xfd\xe7\x0f\xbfF\xff\xfe\xdb\x1f\xbf\xfb\xfc\x8b\\\xba%\xe9\x18\x98,3\xbc\xfd\xcbo\xde\xfe\xe3\x9f\xdf+@Y\xc8\xbe\xfc\xea\xed\xd7_}\xfb\xfb\xdf\xfe\xeb\xcf\x9fW\xad?\x12pV\xa6_\x90\x14K\xf4\x18_\xa2g<\xd5JV\xe8\x80\xcf\xc4{\xb2,\x12 \x16\x0b$<\x85\xaa\xc5\xa7*\xb1(\x1fo\x81V\x12\x8e\xb1m\xc9\x17\x82\xb0e%\xe5\x83\xcdK\x0b\xef<\x11\x1bE\xaa\x84?JR\x8b\xf2\x94s:\xe6\xa2\xda\x0c\x8f\x8c\xb8"\xf4\x16\x1b\x16\xd7\xc8\x17\x9b\xb2\xf2\xcf\x00.*\xc5\x87\xd7|=\xdd\xac\x13\x9c\x92\xcaE\xc3\x04[P\x9fR`\nb\xcc\xb0B\xfa\x19?\xc7\xb8J\xc5O\x08\xb1\xec{J"\xc1%_)\xf4\tAc \xd5\x86Y\x903+\xaa\n\xaec\x92\x02\x85m%\xc6E\x02PV\xfc\xf4\x05\x1asZ\xa9\xfa\x04_\xd8\xa4\xc0b\xa0U\n,0\xb5\xac\xf9\x006\n\xd2\xcaE\x17\x90\xd2\xb2\xfc\x13PI%\xd0\xf9VDe\xc2\xa9T\x02X\x8c)G\xd3%\x96\xb2\x92\xe9\x89\xd0Z\x17\xfe\x7f\x04\x94\xd4D\xc0)\xdd\xa66\xa9P\xe4\xbcr\xd5\x13\xe0\xbcL:\xe1\xe7a\x02\xe9\xba\x1a7aI\x99\xf8cy\xce9\x05\xf4\x94\xabJ\xfaSn\xef\x19}\xcd)\x01V\xef\xf9\x17\x04[\x9e\xbfA~xNb\x0bU\x11,\xfa\xc9FTy\xf5\x01\xe6\xf6\x1e\xdd\xd2\x15\xe0\xca\xf43\x12\xa9\x95{G\x82TG\xcax\x13[\xa1~\x821\x85KXb\x8c\x9e\x7f\\\x05b\xcc\xd7\x96\xed\x0b\xe0\x0f\x13\xcc\xe2c\\\x19e\x0f\xc1\x0e]}\xcd\xb0\xc4(\xeb\x89\x0e\xf3\xe7\t\x91V\x04\xcfq\xcc\xeb \x9dn\xafe\xa4-\xb0\x14D\xed\xda\x8f\xcf\xed\xf0\x99\x9e\tR\x9dh\x9f\xd0\xe8\xbc\x1c;\x8f\x89\xd0;\xb9\xc64O\xa4^\xa5\x08\xf6\xfau\x9f&`U8}-k\xc2w+,O\xdeh\xdb\xcd\xb7\xe2\xe5{\xef\xd5\xf9V\xe0\xf7g\xe2\xc2\xd2\xf9\xfb-\xb4\x00j\x89(\x82g\x01\x04\x9dT&\xe3\x05\xd8\xb9\xac\xe0\xd1\x05\xd8\xf0m\xaa\x19W\xf6F.\xb9\xc3\x85\xa1\xd5!\xa5\x84\xbd\xb3]\xba\xd6(\xf9?Y\xa3T\xd3\xf1\xdcF\x8bT\xb3\xf4\x075G\xb5\xa9\xe6\xf8ZKTK\xf8?\xda\x08M`\xc3\x9eb]l\x0e\xd3\xd9]\x1f\xa4\xbb\xa7\xbb>h\xf7\x17\xec\xff\xa3\x0f\xaa\xdd\xe1w\xdd\xcf]\xf7S\xf4Iw\xdd\xcfO\xdf\xfd\x14\r\x8f[\x9e*\x99YLz\xa3\x11\xd3\x8aP:W[\x8aO\xa4\x992IN\xc9rF(5\xc303\'\xdd\x0f"\xd7IH\xb3\xbf4.\x0c-\xc2X\x80aB\x82\xab_\x11\x95\xcc\x13X\xe3\xc0i\x9aIj,\xf3\xb5c\x89\xd6\\\x06\x8egn\x9bY/\xbe\xb6\xb8\x19tm\xd2S\xbe\xccF\xae\xcd\xa6\x1e\xaf\xe6\xb5X\x82*\x1ex~\xf1@\x11\xa62\xfan\xaf4A\xdcK0\xa3\xd9\xd8L\x7fw\x184\xf7\xfb\xe0(\x8b\xb3q\xb4\xabp\xf4\xf6w\xb5\xa9vf\xac\xc0a\xf4\xbb\x1d \x83* }-`7\x91<\x04\xe2\xc2p\xef\x1eJ\x18\x02=\xb9\xf7;\xf9L[F@\xf1R;,\x1fo\xef\xfc\xac\xddt\xab>\xaf5)-\x07\x83\xd7\xaaRq\xa0\xe1\xd6\xab\xa85\xcc\xe2\xee\x06>\xb7p\x94c\xcf\xc6Q\x0e\xca\x04\x968\x0fV\xebU\xc0mz}P\xf2\xad\x05Q\x1bd\xbf=\n$\xbd\xfe\x8f\xe3u\x9de\xae%\x0c\xca\xca\xe9\x832t\x198\xdd\xb6\xef9(\x82u\xe0\xac((\x07E\xe9z\x198R\xff\x93\x03\x1a\xb3\xc0\x89\x94\xc8\x92\xc0\x0fJ7k!\xd5\x04d\x92\x99\xddd\xa2<E\xa4Da\x81(I\x03G\x9b\xa0\x88\x0b\xcaLj1\xf0\x9a\xad\x9e~\xf0\xf3\xc57\xf0~\x96\xf6sah{\x1b\xafV8Re\xff\x97\xeeh{g\x97\'R\xe5\xf9\xa3\xf2\xb1\xe1\xff\x00j\xcd\xca7\n\x8by\xb2\xbcDgt#\x9e\xc12p\xfc^S[qI\xa4\n\x9cff\xd2%\x11\xa5\xf4V\x84\xe2\xb5\xba\x95\xe7\xe3\xf2\xeb\xb2\xfc5\x9f\x96\x05t\x9d@^n\xac4\x9f\xd1\x9b$\xbf\xc7c\xae\xf6f(]\xe5Z\xbb;#\x95\xadx\x16\xeb\n\xfc\xe1e\xf9\xdd\xc5\\\xebST\xcfA\xa9\xa6ZiFW\xd5\x9a\x14\xfb\xe3\xf5\x01%\\\xa5\x1ak\xe1\xca2z\xf6O]\x16\xe9o\xb0O\x7f0\xac) \xef(\xcb7(\x15%x%q\x16<\r\xbb";\xebd\xbe\xbbm\xc3\xbb\xcd\xae\xa1d\x8fn\x9d\xfd\x8a\xf2Qi\x8f\x1f\xdc\x1d\xb80\xbc\x1e\xc3\xbat\xecZR\xb3\r\xcc\t\x80\xf2\x8by~\xf6\x12Gj\x82W\xb0\xa1JfN\xc5WJ@\xb8{c\x9f\'\x12\x18\xe2+\x95\xf7\x94\xf8J\xa1\x8d \x81\xf3\xa9\xe7\x8f:a\xcb\x0f\x1b^\xdf\x9f6:\xed\x8e\xd7\xe8\xfb\xa3vc\xe4\xfb\xed\xe6\xd4oz\x93q\xeb\x95st_%i\xd3\xcf\xce\x1f\xcc %t\x9b\x9fB0\xf7\x0fN"\xa4\xbb\x97F\xf7"\x9e\xba\xdc\x9c4p\rts\x12\xa1\xd9\xba\xd9I\x04D\x96\x81\xf3i\xb75\x1b\xb4\x07\xe3nc\xd0\x1e\xcd\x1a\x9d\xc9\xb8\xdf\x18\x84\xddqc\xd2\r{\x93\xd9$\xf4\xfb\x83\xd9+\x07]\x18\xe2\xce\xa8\x1dv\xba\xd3~\xa3\xdb\x0c\xc3F\xa7\xebiU\xfa\x83F\xaf\xd3j\x8d:\xbdQ\x7f\xda\x19\xbd\xda\xb5=\xf8Je\xb9%7\x8c\x9b\x9f\xb08\xfa/\x00\x00\x00\xff\xff\x03\x00PK\x03\x04\x14\x00\x06\x00\x08\x00\x00\x00!\x00\\H\x0fk%\x08\x00\x00vB\x00\x00\r\x00\x00\x00xl/styles.xml\xcc\\\xdfo\xab6\x18}\x9f\xb4\xff\x01Y\xdac\xcao\x02U\xc8\xd4\xa4e\xbb\xd2]w\xa5\xdbi\xf7\x95\x10\'\xf5jp\x04\xce]\xb2i\xff\xfbdL\xb0\xdd&\x8d\x9b\xd2\x10\xf5\xa1\x94\xe2\xe3\xf3}\xe7\xf3\xb11!\xa3\x9f796\xbe\xc3\xb2B\xa4\x88\x81}e\x01\x03\x16\x19\x99\xa3b\x19\x83?\x1e\x92A\x08\x8c\x8a\xa6\xc5<\xc5\xa4\x801\xd8\xc2\n\xfc<\xfe\xf1\x87QE\xb7\x18~}\x84\x90\x1a\x9b\x1c\x17U\x0c\x1e)]]\x9bf\x95=\xc2<\xad\xae\xc8\n\x16\x9b\x1c/H\x99\xa7\xb4\xba"\xe5\xd2\xacV%L\xe7\x15k\x94c\xd3\xb1\xac\xc0\

In [5]:
df=pd.read_excel('heartdisease exp 8.xlsx')
df.head()

   age  Gender  Family  diet  Lifestyle  cholestrol  heartdisease
0    0       0       1     1          3           0             1
1    0       1       1     1          3           0             1
2    1       0       0     0          2           1             1
3    4       0       1     1          3           2             0
4    3       1       1     0          0           2             0

In [6]:
df.shape

(19, 7)

In [7]:
df.isnull().sum()

age             0
Gender          0
Family          0
diet            0
Lifestyle       0
cholestrol      0
heartdisease    0
dtype: int64

In [8]:
dtype:np.int64
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   age           19 non-null     int64
 1   Gender        19 non-null     int64
 2   Family        19 non-null     int64
 3   diet          19 non-null     int64
 4   Lifestyle     19 non-null     int64
 5   cholestrol    19 non-null     int64
 6   heartdisease  19 non-null     int64
dtypes: int64(7)
memory usage: 1.2 KB

In [9]:
df.describe()

,age,Gender,Family,diet,Lifestyle,cholestrol,heartdisease
count,19.000000,19.000000,19.000000,19.000000,19.000000,19.000000,19.000000
mean,2.157895,0.473684,0.736842,0.578947,1.473684,0.947368,0.578947
std,1.537066,0.512989,0.452414,0.507257,1.306753,0.911268,0.507257
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.000000,0.000000,0.500000,0.000000,0.000000,0.000000,0.000000
50%,2.000000,0.000000,1.000000,1.000000,2.000000,1.000000,1.000000
75%,3.500000,1.000000,1.000000,1.000000,3.000000,2.000000,1.000000
max,4.000000,1.000000,1.000000,1.000000,3.000000,2.000000,1.000000

In [10]:
df.columns

Index(['age', 'Gender', 'Family', 'diet', 'Lifestyle', 'cholestrol',
       'heartdisease'],
      dtype='object')

In [12]:
!pip install pgmpy==1.0.0
import pgmpy
print(pgmpy.__version__)

Requirement already satisfied: pgmpy==1.0.0 in /usr/local/lib/python3.13/dist-packages (1.0.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.13/dist-packages (from pgmpy==1.0.0) (3.6.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (from pgmpy==1.0.0) (2.1.3)
Requirement already satisfied: scipy in /usr/local/lib/python3.13/dist-packages (from pgmpy==1.0.0) (1.16.3)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.13/dist-packages (from pgmpy==1.0.0) (1.6.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (from pgmpy==1.0.0) (2.2.3)
Requirement already satisfied: torch in /usr/local/lib/python3.13/dist-packages (from pgmpy==1.0.0) (2.11.0+cpu)
Requirement already satisfied: statsmodels in /usr/local/lib/python3.13/dist-packages (from pgmpy==1.0.0) (0.14.6)
Requirement already satisfied: tqdm in /usr/local/lib/python3.13/dist-packages (from pgmpy==1.0.0) (4.67.3)
Requirement already satisfied: joblib in /usr/local/lib/python3.13/dist-packages (from pgmpy==1.0.0) (1.5.3)
Requirement already satisfied: opt-einsum in /usr/local/lib/python3.13/dist-packages (from pgmpy==1.0.0) (3.4.0)
Requirement already satisfied: pyro-ppl in /usr/local/lib/python3.13/dist-packages (from pgmpy==1.0.0) (1.9.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas->pgmpy==1.0.0) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas->pgmpy==1.0.0) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas->pgmpy==1.0.0) (2026.3)
Requirement already satisfied: pyro-api>=0.1.1 in /usr/local/lib/python3.13/dist-packages (from pyro-ppl->pgmpy==1.0.0) (0.1.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.13/dist-packages (from torch->pgmpy==1.0.0) (3.32.3)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.13/dist-packages (from torch->pgmpy==1.0.0) (4.16.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.13/dist-packages (from torch->pgmpy==1.0.0) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.13/dist-packages (from torch->pgmpy==1.0.0) (1.14.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.13/dist-packages (from torch->pgmpy==1.0.0) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.13/dist-packages (from torch->pgmpy==1.0.0) (2025.3.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn->pgmpy==1.0.0) (3.6.0)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.13/dist-packages (from statsmodels->pgmpy==1.0.0) (1.0.2)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.13/dist-packages (from statsmodels->pgmpy==1.0.0) (26.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas->pgmpy==1.0.0) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.13/dist-packages (from sympy>=1.13.3->torch->pgmpy==1.0.0) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from jinja2->torch->pgmpy==1.0.0) (3.0.3)
1.0.0

In [18]:
from pgmpy.models import DiscreteBayesianNetwork
from pgmpy.estimators import MaximumLikelihoodEstimator

# Define the structure of the Bayesian Network
# Removed the edge ('heartdisease', 'Lifestyle') to break the loop
model = DiscreteBayesianNetwork([
    ('age', 'heartdisease'),
    ('Gender', 'heartdisease'),
    ('Family', 'heartdisease'),
    ('diet', 'heartdisease'),
    ('Lifestyle', 'heartdisease'), # Keeping this edge, assuming Lifestyle influences heartdisease
    ('cholestrol', 'heartdisease')
])

# Fit the model using the MaximumLikelihoodEstimator
model.fit(df, estimator=MaximumLikelihoodEstimator)

# Print the Conditional Probability Distribution for 'heartdisease'
print(model.get_cpds('heartdisease'))

+-----------------+---------------+-----+---------------+---------------+
| Family          | Family(0)     | ... | Family(1)     | Family(1)     |
+-----------------+---------------+-----+---------------+---------------+
| Gender          | Gender(0)     | ... | Gender(1)     | Gender(1)     |
+-----------------+---------------+-----+---------------+---------------+
| Lifestyle       | Lifestyle(0)  | ... | Lifestyle(3)  | Lifestyle(3)  |
+-----------------+---------------+-----+---------------+---------------+
| age             | age(0)        | ... | age(4)        | age(4)        |
+-----------------+---------------+-----+---------------+---------------+
| cholestrol      | cholestrol(0) | ... | cholestrol(2) | cholestrol(2) |
+-----------------+---------------+-----+---------------+---------------+
| diet            | diet(0)       | ... | diet(0)       | diet(1)       |
+-----------------+---------------+-----+---------------+---------------+
| heartdisease(0) | 0.5           | ... | 0.5           | 0.5           |
+-----------------+---------------+-----+---------------+---------------+
| heartdisease(1) | 0.5           | ... | 0.5           | 0.5           |
+-----------------+---------------+-----+---------------+---------------+

In [20]:
print(model.get_cpds('age'))

+--------+----------+
| age(0) | 0.210526 |
+--------+----------+
| age(1) | 0.157895 |
+--------+----------+
| age(2) | 0.157895 |
+--------+----------+
| age(3) | 0.210526 |
+--------+----------+
| age(4) | 0.263158 |
+--------+----------+

In [21]:
print(model.get_cpds('Gender'))

+-----------+----------+
| Gender(0) | 0.526316 |
+-----------+----------+
| Gender(1) | 0.473684 |
+-----------+----------+

In [22]:
print(model.get_cpds('Family'))

+-----------+----------+
| Family(0) | 0.263158 |
+-----------+----------+
| Family(1) | 0.736842 |
+-----------+----------+